# Generated by Django 2.2.16 on 2021-11-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211114_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='MhLwKDUvQn', max_length=20),
        ),
    ]
